name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    name: Lint, Type Check & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: 20.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}

      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint and format check
        run: |
          npm run lint &
          npm run prettier-check &
          wait

      - name: Type Check
        run: npm run type-check

      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v4
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Send Slack notification for Success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,workflow,took
          text: Published to NPM ${{ steps.publish.outputs.old-version }} -> ${{ steps.publish.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SUCCESS_WEBHOOK_URL }}

      - name: Send Slack notification for Failure
        if: failure() || cancelled()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,workflow,took
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_FAILED_WEBHOOK_URL }}
